version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

