---
log:
  level: "info"
  format: "json"
elixir:
  id: "XC56EL11xx"
  issuer: "http://oidc:9090"
  redirectUri: "http://oidc:31111/elixir/login"
  revocationUrl: "http://oidc:9090"
  secret: "wHPVQaYXmdDHg"
  jwtPrivateKey: "keys/sign-rsa-jwt.key"
  jwtSignatureAlg: "RS256"
cega:
  authUrl: "http://cega:8443/lega/v1/legas/users/"
  id: "dummy"
  jwtIssuer: "http://auth:8080"
  jwtPrivateKey: "keys/sign-jwt.key"
  jwtSignatureAlg: "ES256"
  secret: "dummy"
server:
  cert: "keys/cert.pem"
  key: "keys/key.pem"
s3Inbox: "s3.example.com"
