---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  selector:
    matchLabels:
      run: auth-server
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-server
    spec:
      annotations:
        "vault.hashicorp.com/agent-inject": "true"
        "vault.hashicorp.com/role": "lega-service"
        "vault.hashicorp.com/agent-inject-secret-credentials.yaml": "lega-secrets/auth_creds"
        "vault.hashicorp.com/agent-inject-template-credentials.yaml": |
          {{  with secret "lega-secrets/auth_creds" }}
          elexir:
            id: {{  .Data.elexir_id }}
            secret: {{  .Data.elexir_secret }}
          ega:
            user: {{  .Data.ega_user }}
            pass: {{  .Data.user_pass }}
          {{  end }}
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: auth-server
        image: "novella/sda-auth:test1" 
        ports:
        - containerPort: 8080
        env:
          - name: "LOG_LEVEL"
            value: "DEBUG"
          - name: "ELIXIR_REDIRECT_URI"
            value: "/elixir/login"
          - name: "BIND_ADDRESS"
            value: "0.0.0.0"
          - name: "PORT"
            value: 8080
          - name: "SERVER_NAME"
            value: "login.ega.nbis.se"
          - name: "URL_SCHEME"
            value: "https"
          - name: "DEVELOPMENT"
            value: False
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    run: auth-server
spec:
  type: ClusterIP
  ports:
  - port: 8080 
    targetPort: 8080
  selector:
    run: auth-server
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: login.ega.nbis.se
    http:
      paths:
      - backend:
          serviceName: auth-server
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - login.ega.nbis.se
    secretName: login-ingress-cert