name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16, 1.17, 1.18]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Add oidc to /etc/hosts
      run: |
        sudo echo "127.0.0.1 oidc" | sudo tee -a /etc/hosts
    - name: Start virtual infrastructure
      run: docker-compose -f ./dev-server/docker-compose.yml up -d --force-recreate --build
    - name: Run unit tests
      run: tox -e unit_tests -c tests/tox.ini
